name: Provider_template_v1
description: Provider structure template

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # region [@REQUIRED]
  http: ^0.12.0+4

  logger: ^0.8.3
  get_it: ^3.1.0
  google_fonts: ^0.3.9
  device_info: ^0.4.1+4
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^1.0.2
  cached_network_image: ^2.0.0
  # endregion
  # region [@DYNAMIC]
  # keyboard is open
  keyboard_visibility: ^0.5.6

  # add more features to dart
  dart_extensions: ^0.3.3

  # can help with date format
  intl: ^0.16.1

  # add count of messages to icons
  badges: ^1.1.0

  # dots loader
  dots_indicator: ^1.1.0

  # FaceID and FingerId
  local_auth: ^0.6.1

  # ready shimmer for flutter
  shimmer: ^1.0.1

  # carousel
  carousel_pro: ^1.0.0

  # easy un boardings and intro
  intro_slider: ^2.2.9

  # Check connect to ethernet
  connectivity: ^0.4.6+2

  # Dart API test support
  e2e: ^0.2.4+1


  #endregion

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
